# Generated by Django 2.2.5 on 2021-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210225_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='network.Post'),
        ),
    ]
